### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

site_name: Documentação do Docker
site_description: Documentação do Docker

### navigation ###

nav:
  - Documentação do Docker: index.md
  - Começando:
      - comecando/index.md
      - comecando/obtenha-o-docker.md
      - comecando/o-que-e-docker.md
