### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

site_name: Documentação do Docker
site_description: Documentação do Docker

exclude_docs: |
  comecando/conceitos-do-docker/index.md
  comecando/conceitos-do-docker/o-basico/index.md

### navigation ###

nav:
  - Documentação do Docker: index.md
  - Começando:
      - comecando/index.md
      - comecando/obtenha-o-docker.md
      - comecando/o-que-e-docker.md
      - Introdução:
          - comecando/introducao/index.md
          - comecando/introducao/obtenha-o-docker-desktop.md
          - comecando/introducao/desenvolva-com-conteineres.md
          - comecando/introducao/crie-e-envie-sua-primeira-imagem.md
          - comecando/introducao/o-que-vem-a-seguir.md
      - Conceitos do Docker:
          - O básico:
              - comecando/conceitos-do-docker/o-basico/o-que-e-um-container.md
